live_config_reload = true

[window]
opacity =  0.9
decorations = "Transparent"
padding= {x = 10, y= 60}
option_as_alt = "OnlyLeft"

[font]
size = 18
normal = { family = "Hack Nerd Font", style = "Regular" }
