[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity =  0.9
decorations = "Buttonless"
padding= {x = 10, y= 2}
option_as_alt = "OnlyLeft"

[font]
size = 18
# normal = { family = "MesloLGS NF", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
